config/routes.rb
AlgaeSite::Application.routes.draw do

  devise_for :users

  namespace :admin do
    scope '/:for_locale', constraints: { for_locale: /(#{I18n.available_locales.join('|')})/ } do
      root 'base#index'
      resources :pages
      resources :page_groups
      resources :images
      resources :menus
      resources :statics
      resources :uploads
      resources :locales
    end

    get '/', to: redirect("/admin/#{I18n.default_locale}")
  end

  root to: redirect('/home')

  get '/robots.:format' => 'application#robots'

  scope '(:locale)', constraints: { locale: /(#{I18n.available_locales.join('|')})/ } do

    get '/', to: redirect('/%{locale}/home')

    scope module: :static do
      get :home
      get :sitemap
    end

    resources :pages, only: [ :show ]
    resources :page_groups, path: '', only: [ :show ]
    resources :statics, path: '', only: [ :show ]
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= render 'common/analytics' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Algae Farms Admin</title>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to [:admin, :root], class: 'navbar-brand' do %>
                Algae Farms <small>Admin</small>
            <% end %>
        </div>

        <ul class="nav navbar-nav">
            <li><%= link_to 'Pages', [:admin, :pages] %></li>
            <li><%= link_to 'Page Groups', [:admin, :page_groups] %></li>
            <li><%= link_to 'Images', [:admin, :images] %></li>
            <li><%= link_to 'Menus', [:admin, :menus] %></li>
            <li><%= link_to 'Statics', [:admin, :statics] %></li>
            <li><%= link_to 'Uploads', [:admin, :uploads] %></li>
            <li><%= link_to 'Locales', [:admin, :locales] %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Content language: <%= image_tag language_flag(Locale.current_globalize.code.to_sym), size: '18x18' %> <%= Locale.current_globalize.title %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <% Locale.all.each do |locale| %>
                        <li>
                            <%= link_to params.merge(for_locale: locale.code) do %>
                                <%= image_tag language_flag(locale.code.to_sym), size: '18x18' %>
                                <%= locale.title %>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            </li>
            <li><%= link_to 'Sign out', [:destroy, :user, :session], :method => :delete %></li>
        </ul>
    </nav>
</div>

<div class="container">
    <% if flash[:notice].present? %><div class="alert alert-info"><%= flash[:notice] %></div><% end %>
    <% if flash[:alert].present? %><div class="alert alert-warning"><%= flash[:alert] %></div><% end %>

    <%= yield %>
</div>

<%= javascript_include_tag 'admin' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= render 'common/analytics' %>

    <title>Algae Farms<%= " - #{@page_title}" if @page_title.present? %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js' %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <nav class="menu">
        <div class="logo">
            <%= link_to image_tag('logo.png', width: 140, height: 60), Static.where(action: 'home').first.url %>
        </div>

        <div class="languages">
            <% locales = Locale.all.where(active: true) %>
            <% if locales.size < 2 %>
                &nbsp;
            <% else %>
                <% locales.each do |locale| %>
                    <%= link_to image_tag(language_flag(locale.code.to_sym), size: '16x16'), params.merge(locale: locale.code), class: ('active' if locale == Locale.current) %>
                <% end %>
            <% end %>
        </div>

        <ul>
            <% @top_menu = Menu.where(title: 'Top').first %>
            <% @top_menu.linkables_menus.zip(@top_menu.linkables_menus[1, @top_menu.linkables_menus.size]).each do |current_item, next_item| %>
                <% more_depth = next_item.present? && next_item.depth > current_item.depth %>
                <% less_depth = next_item.present? && next_item.depth < current_item.depth %>
                <li class="<%= 'last' if less_depth %>">
                    <%= link_to current_item.linkable.title, current_item.linkable.url, current_item.linkable.link_options %>
                    <%= '<nav><ul>'.html_safe if more_depth %>
                    <%= '</ul></nav>'.html_safe if less_depth %>
                </li>
            <% end %>
        </ul>
    </nav>

    <div class="clear"></div>

    <div class="cookies" id="cookies" style="display: none;">
        Για να επιτύχουμε την καλύτερη δυνατή εμπειρία χρήσης αυτού του ιστότοπου, κάνουμε χρήση Cookies. Συνέχεια της χρήσης του ιστότοπου ισοδυναμεί με αυτόματη αποδοχή των Cookies.
        <br />
        <input type="button" value="Εντάξει" id="cookies-ok">
    </div>

    <%= yield %>

    <div class="clear"></div>

    <nav class="menu-bottom">
        <% @bottom_menu = Menu.where(title: 'Bottom').first %>
        <% @bottom_menu.linkables_menus.each_with_index do |current_item, index| %>
            <%= link_to current_item.linkable.title, current_item.linkable.url, current_item.linkable.link_options %>
            <%= '/' unless @bottom_menu.linkables_menus.size - 1 == index %>
        <% end %>
    </nav>

    <div class="copyright">
        Copyright &copy; <%= Time.zone.now.year %>, ALGAE FARMS, All rights reserved.
    </div>
</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= render 'common/analytics' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Algae Farms Admin</title>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to admin_root_path(for_locale: params[:for_locale] || I18n.default_locale), class: 'navbar-brand' do %>
                Algae Farms <small>Admin</small>
            <% end %>
        </div>
    </nav>
</div>

<div class="container">
    <% if flash[:notice].present? %><div class="alert alert-info"><%= flash[:notice] %></div><% end %>
    <% if flash[:alert].present? %><div class="alert alert-warning"><%= flash[:alert] %></div><% end %>

    <%= yield %>
</div>

<%= javascript_include_tag 'admin' %>
</body>
</html>